version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: >
      sh -c "
      python3 manage.py migrate_schemas &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django.env
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./compose/local/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - ./.envs/.local/.postgres.env
    ports:
      - '5432:5432'

volumes:
    static_volume:
    media_volume:
    postgres_data:
