# Generated by Django 3.0.8 on 2021-09-03 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210904_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_liked_users',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_liked_users',
            field=models.ManyToManyField(blank=True, related_name='post_liked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
