# Generated by Django 3.0.8 on 2021-09-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210904_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='posts',
            name='activity_type',
            field=models.ManyToManyField(blank=True, related_name='post_activity_users', to='users.ActivityType'),
        ),
    ]
