# Generated by Django 3.0.8 on 2021-09-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_posts_post_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_stat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
